# Generated by Django 5.1.5 on 2025-02-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='activation_code',
            new_name='otp_code',
        ),
        migrations.AddField(
            model_name='user',
            name='last_otp_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
