# Generated by Django 5.1.5 on 2025-03-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_activation_code_user_otp_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='staff_images/')),
                ('quote', models.TextField()),
                ('role', models.CharField(choices=[('DIRECTOR', 'Director'), ('HEAD', 'Head'), ('STAFF', 'Staff')], max_length=10)),
                ('department', models.CharField(choices=[('TECHNICAL', 'Technical'), ('MARKETING', 'Marketing'), ('SCIENTIFIC', 'Scientific'), ('EXECUTIVE', 'Executive'), ('MEDIA', 'Media'), ('DECORATION', 'Decoration'), ('GRAPHICS', 'Graphics')], max_length=15)),
            ],
        ),
    ]
