# Generated by Django 5.1.5 on 2025-03-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_staff_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='team',
            field=models.CharField(choices=[('TECHNICAL', 'Technical'), ('MARKETING', 'Marketing'), ('SCIENTIFIC', 'Scientific'), ('EXECUTIVE', 'Executive'), ('MEDIA', 'Media'), ('DECORATION', 'Decoration'), ('GRAPHICS', 'Graphics'), ('DIRECTOR', 'Director')], max_length=15),
        ),
    ]
