# Generated by Django 5.1.5 on 2025-03-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_faq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='accessories',
            field=models.ManyToManyField(related_name='accessories', to='accounts.accessory'),
        ),
    ]
