# Generated by Django 5.1.5 on 2025-03-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_accessory_user_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='accessory',
            name='stock',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='price',
            field=models.FloatField(default=10000),
        ),
    ]
