# Generated by Django 5.1.5 on 2025-03-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_accessory_img_accessory_stock_alter_accessory_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='stock',
        ),
    ]
