# Generated by Django 5.1.5 on 2025-03-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_accessory_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='accessories', to='accounts.accessory'),
        ),
    ]
