# Generated by Django 5.1.5 on 2025-04-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
