# Generated by Django 5.1.5 on 2025-04-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_staff_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
