# Generated by Django 5.1.5 on 2025-04-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_accessory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_signed_up_for_competition',
            field=models.BooleanField(default=False),
        ),
    ]
