# Generated by Django 5.1.5 on 2026-10-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_is_signed_up_for_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
    ]
