# Generated by Django 5.1.5 on 2026-10-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_accessory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hamkaran_announcement_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='heard_about_us',
            field=models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('friends', 'Friends / Word of Mouth'), ('university', 'University / Posters'), ('hamkaran', 'Hamkaran System'), ('website', 'LinuxFest Website / Search Engine'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_purpose',
            field=models.CharField(blank=True, choices=[('email_verification', 'Email verification'), ('password_reset', 'Password reset')], max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
