# Generated by Django 5.1.5 on 2025-03-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_payment_participations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='hashed_card_number',
            new_name='card_pan',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_link',
            new_name='pay_link',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paymentID',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='trackID',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verifyID',
        ),
        migrations.AddField(
            model_name='participation',
            name='has_accessories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='authority',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ref_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='accessories',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentation',
            name='accessories_capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentation',
            name='accessories_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percentage',
            field=models.IntegerField(default=0.0, help_text='Enter a number between 0 to 100.'),
        ),
    ]
