# Generated by Django 5.1.5 on 2025-03-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_hashed_card_number_payment_card_pan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='coupon',
        ),
    ]
