# Generated by Django 5.1.5 on 2025-03-24 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_payment_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='coupon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.coupon'),
        ),
    ]
