# Generated by Django 5.1.5 on 2025-03-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_payment_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='has_accessories',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='accessories_capacity',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='accessories_cost',
        ),
    ]
