# Generated by Django 5.1.5 on 2025-03-27 09:14

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_payment_accessories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='presenter',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
