# Generated by Django 5.1.5 on 2025-03-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_presentationtag_presentation_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenter',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
