# Generated by Django 5.1.5 on 2025-03-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_presenter_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='presentation_tag', to='shop.presentationtag'),
        ),
    ]
