# Generated by Django 5.1.5 on 2025-03-28 16:24

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_presentation_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationtag',
            name='color',
            field=colorfield.fields.ColorField(default='#FA175C', image_field=None, max_length=25, samples=None),
        ),
    ]
