# Generated by Django 5.1.5 on 2025-04-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_description_presentation_en_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_competition_payment',
            field=models.BooleanField(default=False),
        ),
    ]
