# Generated by Django 5.1.5 on 2026-10-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_payment_is_competition_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='authority',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
