# Generated by Django 5.1.5 on 2026-10-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_bilingual_presentation_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='eligible_presentations',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to apply this coupon to the whole cart.', related_name='coupons', to='shop.presentation'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='preserve_capacity',
            field=models.BooleanField(default=False, help_text="When enabled, registrations discounted by this coupon do not reduce the selected presentations' remaining capacity."),
        ),
        migrations.AddField(
            model_name='participation',
            name='is_capacity_exempt',
            field=models.BooleanField(default=False, help_text='Completed registrations with this flag do not reduce remaining capacity.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='coupon_participations',
            field=models.ManyToManyField(blank=True, help_text="Snapshot of participations to which this payment's coupon applied.", related_name='coupon_payments', to='shop.participation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='coupon_preserves_capacity',
            field=models.BooleanField(default=False, help_text="Snapshot of the coupon's capacity behavior when checkout started."),
        ),
    ]
