# Generated by Django 5.1.5 on 2026-10-07 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_presentationproposal_slides'),
        ('shop', '0020_coupon_eligible_presentations_and_more'),
    ]

    operations = [
    ]
