# Generated by Django 5.1.5 on 2026-10-09 08:13

import django.core.validators
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_merge_20261007_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationproposal',
            name='slides',
            field=models.FileField(blank=True, upload_to='presentation_proposals/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx']), shop.models.validate_proposal_slide_size, shop.models.validate_proposal_slide_content]),
        ),
    ]
